### ISSUE TITLE
To-do list for foundational setup 🧱

### ISSUE THREAD

**Issue by LauraAubin** [LauraAubin/World-Of-Workflow#1]
## Setup

- [x] Create base application (React and Electron app, make sure it has Typescript)
   - [x] "I can use the application on top of other apps" https://github.com/LauraAubin/World-Of-Workflow/commit/9d13f497e0e1d83870783bac9d8f3eeb5c52b64f
   - [x] "I can show and hide the app with the keyboard, similar to spotlight." https://github.com/LauraAubin/World-Of-Workflow/commit/6fae12ec4a7982aefd51329fe6c6ad83176b566d
   - [x] "I can hide the app when I click outside of it's elements." https://github.com/LauraAubin/World-Of-Workflow/pull/5
- [x] Read and write to a CSV for our DB, create a simple API for this. https://github.com/LauraAubin/World-Of-Workflow/pull/6

I.e,

```js
writeTo('table_name', contents: {message: 'bar'})

// will write the following line,
{table: 'foo', message: 'bar', created_at: Time.now}

// and can be accessed like,
readFrom('foo', conditions: {where: created_at > Time.now})
```
