### ISSUE TITLE
To-do list for functionality 🙈

### ISSUE THREAD

**Issue by LauraAubin** [LauraAubin/World-Of-Workflow#3]
## Create components

- [x] Create list for viewing current quests (top right corner). Instead of type, this will probably be by date. https://github.com/LauraAubin/World-Of-Workflow/commit/e8d630da819a56f296e3ed20854bbe55e214f508
- [x] Create quest description component https://github.com/LauraAubin/World-Of-Workflow/commit/8bed628540cb60576e8f02125f7e949a9651862f
- [ ] Create action items (Does the quest have multiple linear parts? Does it have multiple items to be completed? 0/7 for example)
- [x] Create admin view for creating a new quest (name, description, location, due date, topic (like for school, work, specific class, etc) https://github.com/LauraAubin/World-Of-Workflow/commit/ea9edd45582a0653b7b2ecfb825887f5deba6db3

### Quests
- [x] I can see all available quests for today https://github.com/LauraAubin/World-Of-Workflow/commit/98a36ab3eb565b4890b9576429845ac83139706a
- [x] I can see all available quests for tomorrow if there aren't a lot for today https://github.com/LauraAubin/World-Of-Workflow/commit/98a36ab3eb565b4890b9576429845ac83139706a
- [x] I can view the quest description in the quest popup https://github.com/LauraAubin/World-Of-Workflow/commit/cd67a0d409f3d9fbae80fe2eaa50528b98b12774
- [x] I can hand in the quest, mark it as complete (relies on https://github.com/LauraAubin/World-Of-Workflow/issues/8) https://github.com/LauraAubin/World-Of-Workflow/commit/8fb9ebe5af9b7fc6f50330cff9bd8e7270dbfc68
- [x] I no longer see completed quests in the QuestList https://github.com/LauraAubin/World-Of-Workflow/commit/2df9cd5f4970f562582f43b0c5ac800e42058eeb
- [ ] I can view past completed quests
- [x] I can still see and complete the quest even after missing the deadline
- [ ] I can update the quest (relies on https://github.com/LauraAubin/World-Of-Workflow/issues/8)
   - As a user, I do not want to see edit buttons everywhere (nothing in the quest details view)
   - As the GM, I don't want to do a lot of extra clicking (redirecting focus in and out of the GM window)
   - As a user who notices something I want to quickly update, I want to be able to change it right away
- [ ] I am presented with available quests for me to accept (those with far away deadlines?)
- [ ] I can abandon the quest (is this the same as completing? Or is it more like deleting?)
